# Run three times to get all the updates and validate the package
- name: install cstrike
  shell: steamcmd +login "anonymous" +force_install_dir "./cs" +app_update "90 validate" +quit
  become: no
  ignore_errors: yes

- name: update cstrike
  shell: steamcmd +login "anonymous" +force_install_dir "./cs" +app_update "90 validate" +quit
  become: no
  ignore_errors: yes

- name: validate cstrike
  shell: steamcmd +login "anonymous" +force_install_dir "./cs" +app_update "90 validate" +quit
  become: no
  ignore_errors: yes
