# Run three times to get all the updates and validate the package
- name: install csgo
  shell: steamcmd +login anonymous +force_install_dir "./cs/" +app_update 740 validate +quit
  become: no
  ignore_errors: no

- name: validate csgo
  shell: steamcmd +login anonymous +force_install_dir "./cs/" +app_update 740 validate +quit
  become: no
  ignore_errors: no
