# Make Pavlov Script executable
- name: Make Pavlov Script executable
  file:
    path: /home/ubuntu/.steam/steamcmd/pavlovserver/PavlovServer.sh
    mode: a+x

# Create required folders
- name: Create Logs Directory
  file:
    path: /home/ubuntu/.steam/steamcmd/pavlovserver/Pavlov/Saved/Logs
    state: directory

- name: Create LinuxServer Directory
  file:
    path: /home/ubuntu/.steam/steamcmd/pavlovserver/Pavlov/Saved/Config/LinuxServer
    state: directory

- name: Create Maps Directory
  file:
    path: /home/ubuntu/.steam/steamcmd/pavlovserver/Pavlov/Saved/maps
    state: directory

- name: add update_pavlov_shack.sh script
  copy:
    src: ./update_pavlov_shack.sh
    dest: /home/ubuntu/update_pavlov_shack.sh
    owner: ubuntu
    group: ubuntu
    mode: u+rwx,g+rwx,o+rwx
  when: installation_type == "pavlov_shack"

- name: add start script for pavlov_shack
  copy:
    src:  ./start_pavlov_shack.sh
    dest: /home/ubuntu/start_pavlov_shack.sh
    mode: 0644
    owner: ubuntu
    group: ubuntu
    mode: u+rwx,g+rwx,o+rwx
  when: installation_type == "pavlov_shack"


# Add custom maps from a file
# commandline to generate file?
# if file exists iterate through the content of the file
# download the files and put them in the correct place
# update the game.ini to use all the custom maps

# http://download2265.mediafire.com/1l2pt6sqfftg/3ld3pzs0mwfhdrj/SVR_john_nuketown.zip
# http://download662.mediafire.com/yq2dzb9iu6jg/qur1yb4obfusfq2/SVR_john_mcdonalds.zip

# - name: register maps
#   shell: "echo {{items}}"
#   loop: "{{ lookup('file', 'files/maps.txt').splitlines() }}"
#   register: map_urls

# - name: install maps from file
#   get_url:
#     url: "{{item}}"
#     dest: /home/ubuntu/.steam/steamcmd/pavlovserver/Pavlov/Saved/maps
#     mode: '0440'
#     loop: "{{ lookup('file', 'files/maps.txt').splitlines() }}"


# Configure Game.ini
- name: configure Game.ini
  template:
    src: Pavlov_Game.j2
    dest: /home/ubuntu/.steam/steamcmd/pavlovserver/Pavlov/Saved/Config/LinuxServer/Game.ini
    mode: a+rw
    force: yes
    backup: no
