# 1 download steamCMD
- name: Download steamCMD
  get_url:
    url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
    mode: 0550
    dest: /home/ec2-user/steamcmd_linux.tar.gz

# 2 install packages via yum
- name: install required packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - glibc.i686
    - libstdc++.i686

# 3 update iptables
- name: Allow ingress first set
  iptables:
    action: append
    chain: INPUT
    destination_port: 1025:65355
    source_port: 27000:27030
    protocol: udp
    match: udp
    jump: ACCEPT

- NAME: Allow ingress second set
  iptables:
    action: append
    chain: INPUT
    destination_port: 1025:65355
    source_port: 4300
    protocol: udp
    match: udp
    jump: ACCEPT

# 4 untar
- name: Untar steamcmd archive
  unarchive:
    src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
    dest: /home/ec2-user
    remote_src: yes

# 5 run a script
- name: launch steamCMD
  shell: ./steamcmd.sh +login anonymous +force_install_dir ./27020/ +app_set_config 90 mod cstrike +app_update 90 validate +app_update 90 -beta beta validate +quit

- name: start server
  shell: ./hlds_run -console -game cstrike +port 27020 +map de_dust2 +maxplayers 32 -pingboost 1
  chdir: ./27070

# 6 update lc.local or similar in order to have it automatically start server
# later
