# Run three times to get all the updates and validate the package
- name: update steamcmd
  shell: steamcmd +quit

- name: install cstrike
  shell: steamcmd +login "anonymous" +force_install_dir "./cs16server" +app_update "90 validate" +quit
  ignore_errors: yes

- name: update cstrike
  shell: steamcmd +login "anonymous" +force_install_dir "./cs16server" +app_update "90 validate" +quit
  ignore_errors: yes

- name: validate cstrike
  shell: steamcmd +login "anonymous" +force_install_dir "./cs16server" +app_update "90 validate" +quit
  ignore_errors: yes

# TASK [cstrike : create listip.cfg] *************************************************************************************************************************************************************************
# fatal: [server_ip]: FAILED! => {"changed": false, "msg": "Error, could not touch target: [Errno 2] No such file or directory: b'/home/ansible/.stream/steamcmd/c16server/listip.cfg'", "path": "/home/ansible/.stream/steamcmd/c16server/listip.cfg", "state": "absent"}

- name: create listip.cfg
  file:
    path: /home/ansible/.stream/steamcmd/c16server/listip.cfg
    state: touch
    mode: u=rw,g=r,o=r

- name: create banned.cfg
  file:
    path: /home/ansible/.stream/steamcmd/c16server/listip.cfg
    state: touch
    mode: u=rw,g=r,o=r

- name: set rcon_password
  shell: echo rcon_password {{ rcon_password }} > /home/ansible/.stream/steamcmd/c16server/listip.cfg

- name: Ansible create file with content example
  copy:
    dest: "/home/ansible/.stream/steamcmd/c16server/server.cfg"
    content: |
      rcon_password {{ rcon_password }}

- name: add systemctl file for cstrike
  template:
    src: cstrike.j2
    dest: /etc/systemd/system/cstrike.service
    mode: 0644
    force: yes
    backup: no

- name: enable cstrike service
  systemd:
    name: cstrike
    enabled: yes

- name: restart cstrike 1st time
  systemd:
    state: restarted
    daemon_reload: yes
    name: cstrike

- name: restart cstrike 2nd time
  systemd:
    state: restarted
    name: cstrike