# Run three times to get all the updates and validate the package
- name: install cscz
  shell: steamcmd +login "anonymous" +force_install_dir "./cs/" +app_update 90 +app_set_config 90 mod czero validate +quit
  become: no
  ignore_errors: yes

- name: update cscz
  shell: steamcmd +login "anonymous" +force_install_dir "./cs/" +app_update 90 +app_set_config 90 mod czero validate +quit
  become: no
  ignore_errors: yes

- name: validate cscz
  shell: steamcmd +login "anonymous" +force_install_dir "./cs/" +app_update 90 +app_set_config 90 mod czero validate +quit
  become: no
  ignore_errors: yes
