- name: Allow Ingress to port
  iptables:
    action: append
    chain: INPUT
    destination_port: 7777
    source_port: 0
    protocol: udp
    match: udp
    jump: ACCEPT

- name: Allow ingress second set
  iptables:
    action: append
    chain: INPUT
    destination_port: 8177
    source_port: 0
    protocol: udp
    match: udp
    jump: ACCEPT
    