- name: add i386 architecture
  shell: dpkg --add-architecture i386
  become: yes
  become-user: root

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: upgrade
  apt:
    name: "*"
    state: latest
    force_apt_get: yes

- name: pre-seed questions for steam licence agreement
  shell: echo steam steam/question select "I AGREE" | sudo debconf-set-selections

- name: pre-seed licence for stream licence agreement
  shell: echo steam steam/license note '' | sudo debconf-set-selections

- name: install libsdl2 to prevent steam issues
  apt:
    name: libsdl2-2.0-0:i386

- name: install steamcmd
  apt:
    name: steamcmd

- name: update steamcmd
  become: no
  shell: steamcmd +quit

- name: install unzip
  apt:
    name: unzip
