---
#
# counter-strike-condition-zero server playbook
#

- hosts: fps
  remote_user: ubuntu
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/games"
  roles:
  - install_packages
  - cs_iptables
  - csgo
  - general_cs_tasks
  - cs_post_installation
