---
#
# counter-strike-server playbook
#

- hosts: cstrike
  remote_user: ubuntu
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/games"
  roles:
  - install_packages
  - iptables
  - cstrike1.6
  - general_cs_tasks
  - post_installation
