---
#
# counter-strike-server playbook
#

- hosts: cstrike
  remote_user: ubuntu
  become: yes
  become_user: root
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/games"
  roles:
  - install_packages
  - iptables
  - cstrike1.6
