---
#
# pavlov-shack playbook
#

- hosts: fps
  remote_user: ubuntu
  become: yes
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/games"
  roles:
  - install_packages
  - pavlov_shack
  - pavlov_post_installation
